### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by megawac** [ttsvetko/HTML5-Desktop-Notifications#18]
Along with #10, could you publish to npm for browserify users -- thanks @ttsvetko

**Comment by varmint09** [comment]
+1

**Comment by lsapan** [comment]
+1

**Comment by dbrugne** [comment]
+1

**Comment by sebabass** [comment]
+1

**Comment by yfuks** [comment]
+1

**Comment by jeongsd** [comment]
+1

**Comment by martinRoss** [comment]
+1

**Comment by jeongsd** [comment]
hi guys i'm fork this repository for publishing npm
```
npm install html5-desktop-notifications
```
https://www.npmjs.com/package/html5-desktop-notifications

**Comment by ttsvetko** [comment]
Fixed.

https://www.npmjs.com/package/html5-notification

**Comment by NeXTs** [comment]
@ttsvetko how to import this module?

Let's say I've made `npm i -D html5-notification`
Since I'm using es6 I'd like to import it like
`import 'html-notification'` but it does not work, I guess because `package.json` doesn't contains `main` property.

What are your suggestions regarding how to use it?
